services:
  - type: web
    name: future-me
    env: node
    buildCommand: npm install
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false